### ISSUE TITLE
Pass no works fine on HTTPS

### ISSUE THREAD

**Issue by linkito87** [flexible-agency/php-pkpass#100]
The $pass->create(true) not working on HTTPS protocol. You must click many times to get it to work...
Debugging with the iPhone connected, throw this error:
http load failed, 51/20348 bytes buffer

Removing this line of PKPass.php works perfect on HTTPS.

`header('Content-Length: ' . $size);`

**Comment by tschoffelen** [comment]
Hi @linkito87, sounds like your server is doing something special with the output before sending it to the browser.

Could you submit a PR to take out that line?

**Comment by tschoffelen** [comment]
Fixed in #103.
