### ISSUE TITLE
No longer working on Safari 13

### ISSUE THREAD

**Issue by jason11ac** [flexible-agency/php-pkpass#105]
Process:               Safari [18629]
Path:                  /Applications/Safari.app/Contents/MacOS/Safari
Identifier:            com.apple.Safari
Version:               13.1 (15609.1.20.111.8)
Build Info:            WebBrowser-7609001020111008~2
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Safari [18629]
User ID:               501

Date/Time:             2020-10-09 10:26:42.738 -0700
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     4.4 (17P4281)
Anonymous UUID:        7B24D99D-2F23-B5EF-6725-070CBA32C40E

Sleep/Wake UUID:       46667986-6008-4BE6-BAFF-15E38949A6CF

Time Awake Since Boot: 750000 seconds
Time Since Wake:       740000 seconds

System Integrity Protection: enabled

Crashed Thread:        10  Dispatch queue: com.apple.root.background-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSCoreDataTaggedObjectID isFileURL]: unrecognized selector sent to instance 0x4b'
terminating with uncaught exception of type NSException
abort() called

Any ideas how to fix this? Thank you!

**Comment by tschoffelen** [comment]
Did you ever figure out how to fix this? From the error message it looks like there might be a file path in your pass JSON that isn't valid.

I have successfully used the library recently without any crashes, so I think this one is specific to one use case. If we get more info, happy to reopen this one.
