### ISSUE TITLE
Error encountered error: Unexpected response code 404

### ISSUE THREAD

**Issue by haiworler** [flexible-agency/php-pkpass#108]
Hello friend, and thank you for the prompt response, I wanted to comment that I already set the URL of the web service, but now I’m resizing these logs. 
{
    "logs": [
        "[2021-04-09 09:44:27 -0500] Unregister task (for device 2be6579fae0e4a16590a3243387881f7, pass type pass.com.feria, serial number 614369; with web service url https:\/\/example\/api\/registerPasskit) encountered error: Unexpected response code 404"
    ]
}

Any idea what might be going on ?

**Comment by tschoffelen** [comment]
Looks like the web service URL you're using is not a valid URL: https://example/api/registerPasskit
