### ISSUE TITLE
Invalid data error

### ISSUE THREAD

**Issue by vogaluk** [flexible-agency/php-pkpass#112]
I am getting 2 errors when running example.php on my device. I have followed all steps advised.

Invalid data error reading pass pass.my.pass/123456. Manifest signature did not verify successfully
and
assBook Pass download failed: Error Domain=PKPassKitErrorDomain Code=1 "(null)"

**Comment by tschoffelen** [comment]
Hi there! This error is usually triggered when an invalid certificate is used, or a certificate that doesn't match the Pass ID and Team ID specified in the pass's JSON payload.

**Comment by vogaluk** [comment]
Hi! Yes, I thought this. However everything is correct...

**Comment by vogaluk** [comment]
Also, from step 5, when I drag the cert into keychain, no private key (or arrow) shows...
<img width="315" alt="Screenshot 2021-11-25 at 16 02 35" src="https://user-images.githubusercontent.com/95035211/143472903-1d6347e9-40f5-4bc5-866c-8f1221ce1998.png">

**Comment by tschoffelen** [comment]
Seems like Apple, as per usual, has changed the Keychain access slightly without updating the documentation.

https://help.apple.com/developer-account/#/devbfa00fef7

You will need to select both the private key you created to generate the certificate signing request, and the pass certificate, and export them together as a .p12 file.

**Comment by vogaluk** [comment]
Thanks. Managed to do that now.  Still get the same errors though! 

<img width="1169" alt="Screenshot 2021-11-25 at 16 24 21" src="https://user-images.githubusercontent.com/95035211/143475830-39f0f3e8-b917-456c-a2af-5cb921efdec3.png">

**Comment by tschoffelen** [comment]
The pass type ID that is shown in the keychain screenshot doesn't match the pass type ID in the log in your last comment. That might be related?
